### ISSUE TITLE
DependencyAttribute not supported

### ISSUE THREAD

**Issue by MistyKuu** [DaniilSokolyuk/DS.Unity.Extensions.DependencyInjection#1]
When trying to resolve class which has DependencyAttribute in constructor parameters it will not work because it will not find implementation of this parameter. The issue is in this line                         https://github.com/DaniilSokolyuk/DS.Unity.Extensions.DependencyInjection/blob/5f33afa31c08d1485b783cda0877a630624d913e/src/DS.Unity.Extensions.DependencyInjection/UnityExtensions/ConstructorSelectionUnityExtension.cs#L103

CanResolve should check if it contains DependencyAttribute and if it has then check if it's registered with this name. Something along these lines

```
  private bool CanResolve(IUnityContainer container, ParameterInfo arg)
                {
                    var dependencyAttributes = arg.GetCustomAttributes(false).OfType<DependencyAttribute>().ToList();
                    string name = dependencyAttributes.FirstOrDefault()?.Name;
                    
                    if (arg.ParameterType.IsGenericType)
                    {
                        var gerericType = arg.ParameterType.GetGenericTypeDefinition();
                        if ((gerericType == typeof(IEnumerable<>)) ||
                            gerericType.IsClass ||
                            IsRegistered(gerericType))
                        {
                            return true;
                        }
                    }

                    return IsRegistered(arg.ParameterType);

                   bool IsRegistered(Type t) => string.IsNullOrEmpty(name)
                        ? container.IsRegistered(t)
                        : container.IsRegistered(t, name);
                }
```

**Comment by DaniilSokolyuk** [comment]
Hello @MistyKuu 
Thank you, fixed [here](https://github.com/DaniilSokolyuk/DS.Unity.Extensions.DependencyInjection/commit/2220936c38435139da273162a87136a71d33fa65)
I will update the package in 1 hr

**Comment by MistyKuu** [comment]
What if you have named string or enum? Your solution just returns true but it should use named dependency

**Comment by DaniilSokolyuk** [comment]
Fixed here > https://github.com/DaniilSokolyuk/DS.Unity.Extensions.DependencyInjection/commit/f1e28917ae68923d86dc5032afc0d54f857f8079
